# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=0, max_length=30)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pltp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gitload.PLTP')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitload.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50000)),
                ('seed', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('ST', 'Commencé'), ('FA', 'Echoué'), ('SU', 'Réussi')], default='ST', max_length=2)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitload.PL')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=20)),
                ('activity', models.ManyToManyField(to='playexo.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='PLUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ManyToManyField(to='playexo.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(choices=[('AD', 'Administrateur'), ('IN', 'Professeur'), ('CD', 'Concepteur'), ('LE', 'Élève'), ('OB', 'Observeur')], default='LE', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pluser',
            name='role',
            field=models.ManyToManyField(to='playexo.Role'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
