# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0002_add_role_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='pltp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitload.PLTP'),
        ),
    ]
